// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: src/grpc/datakeeper/datakeeper.proto

package datakeeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilePortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename   string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	PortNumber string `protobuf:"bytes,2,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
}

func (x *FilePortRequest) Reset() {
	*x = FilePortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePortRequest) ProtoMessage() {}

func (x *FilePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePortRequest.ProtoReflect.Descriptor instead.
func (*FilePortRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP(), []int{0}
}

func (x *FilePortRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FilePortRequest) GetPortNumber() string {
	if x != nil {
		return x.PortNumber
	}
	return ""
}

type ReplicateFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TcpAddr  string `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"`
	GrpcAddr string `protobuf:"bytes,3,opt,name=grpcAddr,proto3" json:"grpcAddr,omitempty"`
}

func (x *ReplicateFileRequest) Reset() {
	*x = ReplicateFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateFileRequest) ProtoMessage() {}

func (x *ReplicateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateFileRequest.ProtoReflect.Descriptor instead.
func (*ReplicateFileRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReplicateFileRequest) GetTcpAddr() string {
	if x != nil {
		return x.TcpAddr
	}
	return ""
}

func (x *ReplicateFileRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type SuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP(), []int{2}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckFileExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
}

func (x *CheckFileExistsRequest) Reset() {
	*x = CheckFileExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFileExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileExistsRequest) ProtoMessage() {}

func (x *CheckFileExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckFileExistsRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP(), []int{3}
}

func (x *CheckFileExistsRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type FileSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *FileSaveRequest) Reset() {
	*x = FileSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSaveRequest) ProtoMessage() {}

func (x *FileSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_datakeeper_datakeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSaveRequest.ProtoReflect.Descriptor instead.
func (*FileSaveRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP(), []int{4}
}

func (x *FileSaveRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_src_grpc_datakeeper_datakeeper_proto protoreflect.FileDescriptor

var file_src_grpc_datakeeper_datakeeper_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x22, 0x4e, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x68, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x63, 0x70, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x72, 0x22, 0x2b, 0x0a, 0x0f,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x34, 0x0a, 0x16, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x2d, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x81,
	0x02, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x20, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52,
	0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x57, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x73,
	0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_grpc_datakeeper_datakeeper_proto_rawDescOnce sync.Once
	file_src_grpc_datakeeper_datakeeper_proto_rawDescData = file_src_grpc_datakeeper_datakeeper_proto_rawDesc
)

func file_src_grpc_datakeeper_datakeeper_proto_rawDescGZIP() []byte {
	file_src_grpc_datakeeper_datakeeper_proto_rawDescOnce.Do(func() {
		file_src_grpc_datakeeper_datakeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_grpc_datakeeper_datakeeper_proto_rawDescData)
	})
	return file_src_grpc_datakeeper_datakeeper_proto_rawDescData
}

var file_src_grpc_datakeeper_datakeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_grpc_datakeeper_datakeeper_proto_goTypes = []interface{}{
	(*FilePortRequest)(nil),        // 0: datakeeper.FilePortRequest
	(*ReplicateFileRequest)(nil),   // 1: datakeeper.ReplicateFileRequest
	(*SuccessResponse)(nil),        // 2: datakeeper.SuccessResponse
	(*CheckFileExistsRequest)(nil), // 3: datakeeper.CheckFileExistsRequest
	(*FileSaveRequest)(nil),        // 4: datakeeper.fileSaveRequest
}
var file_src_grpc_datakeeper_datakeeper_proto_depIdxs = []int32{
	0, // 0: datakeeper.DataKeeperService.TransferFile:input_type -> datakeeper.FilePortRequest
	1, // 1: datakeeper.DataKeeperService.ReplicateFile:input_type -> datakeeper.ReplicateFileRequest
	3, // 2: datakeeper.DataKeeperService.CheckFileExists:input_type -> datakeeper.CheckFileExistsRequest
	4, // 3: datakeeper.FileSaveService.SaveFile:input_type -> datakeeper.fileSaveRequest
	2, // 4: datakeeper.DataKeeperService.TransferFile:output_type -> datakeeper.SuccessResponse
	2, // 5: datakeeper.DataKeeperService.ReplicateFile:output_type -> datakeeper.SuccessResponse
	2, // 6: datakeeper.DataKeeperService.CheckFileExists:output_type -> datakeeper.SuccessResponse
	2, // 7: datakeeper.FileSaveService.SaveFile:output_type -> datakeeper.SuccessResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_grpc_datakeeper_datakeeper_proto_init() }
func file_src_grpc_datakeeper_datakeeper_proto_init() {
	if File_src_grpc_datakeeper_datakeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_grpc_datakeeper_datakeeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_grpc_datakeeper_datakeeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicateFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_grpc_datakeeper_datakeeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_grpc_datakeeper_datakeeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFileExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_grpc_datakeeper_datakeeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_grpc_datakeeper_datakeeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_src_grpc_datakeeper_datakeeper_proto_goTypes,
		DependencyIndexes: file_src_grpc_datakeeper_datakeeper_proto_depIdxs,
		MessageInfos:      file_src_grpc_datakeeper_datakeeper_proto_msgTypes,
	}.Build()
	File_src_grpc_datakeeper_datakeeper_proto = out.File
	file_src_grpc_datakeeper_datakeeper_proto_rawDesc = nil
	file_src_grpc_datakeeper_datakeeper_proto_goTypes = nil
	file_src_grpc_datakeeper_datakeeper_proto_depIdxs = nil
}
