// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: src/grpc/datakeeper/datakeeper.proto

package datakeeper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataKeeperServiceClient is the client API for DataKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataKeeperServiceClient interface {
	TransferFile(ctx context.Context, in *FilePortRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	ReplicateFile(ctx context.Context, in *ReplicateFileRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	CheckFileExists(ctx context.Context, in *CheckFileExistsRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	DownloadChunk(ctx context.Context, in *DownloadChunkRequest, opts ...grpc.CallOption) (*DownloadChunkResponse, error)
}

type dataKeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataKeeperServiceClient(cc grpc.ClientConnInterface) DataKeeperServiceClient {
	return &dataKeeperServiceClient{cc}
}

func (c *dataKeeperServiceClient) TransferFile(ctx context.Context, in *FilePortRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/datakeeper.DataKeeperService/TransferFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataKeeperServiceClient) ReplicateFile(ctx context.Context, in *ReplicateFileRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/datakeeper.DataKeeperService/ReplicateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataKeeperServiceClient) CheckFileExists(ctx context.Context, in *CheckFileExistsRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/datakeeper.DataKeeperService/CheckFileExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataKeeperServiceClient) DownloadChunk(ctx context.Context, in *DownloadChunkRequest, opts ...grpc.CallOption) (*DownloadChunkResponse, error) {
	out := new(DownloadChunkResponse)
	err := c.cc.Invoke(ctx, "/datakeeper.DataKeeperService/DownloadChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataKeeperServiceServer is the server API for DataKeeperService service.
// All implementations must embed UnimplementedDataKeeperServiceServer
// for forward compatibility
type DataKeeperServiceServer interface {
	TransferFile(context.Context, *FilePortRequest) (*SuccessResponse, error)
	ReplicateFile(context.Context, *ReplicateFileRequest) (*SuccessResponse, error)
	CheckFileExists(context.Context, *CheckFileExistsRequest) (*SuccessResponse, error)
	DownloadChunk(context.Context, *DownloadChunkRequest) (*DownloadChunkResponse, error)
	mustEmbedUnimplementedDataKeeperServiceServer()
}

// UnimplementedDataKeeperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataKeeperServiceServer struct {
}

func (UnimplementedDataKeeperServiceServer) TransferFile(context.Context, *FilePortRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFile not implemented")
}
func (UnimplementedDataKeeperServiceServer) ReplicateFile(context.Context, *ReplicateFileRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateFile not implemented")
}
func (UnimplementedDataKeeperServiceServer) CheckFileExists(context.Context, *CheckFileExistsRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFileExists not implemented")
}
func (UnimplementedDataKeeperServiceServer) DownloadChunk(context.Context, *DownloadChunkRequest) (*DownloadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadChunk not implemented")
}
func (UnimplementedDataKeeperServiceServer) mustEmbedUnimplementedDataKeeperServiceServer() {}

// UnsafeDataKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataKeeperServiceServer will
// result in compilation errors.
type UnsafeDataKeeperServiceServer interface {
	mustEmbedUnimplementedDataKeeperServiceServer()
}

func RegisterDataKeeperServiceServer(s grpc.ServiceRegistrar, srv DataKeeperServiceServer) {
	s.RegisterService(&DataKeeperService_ServiceDesc, srv)
}

func _DataKeeperService_TransferFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServiceServer).TransferFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datakeeper.DataKeeperService/TransferFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServiceServer).TransferFile(ctx, req.(*FilePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataKeeperService_ReplicateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServiceServer).ReplicateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datakeeper.DataKeeperService/ReplicateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServiceServer).ReplicateFile(ctx, req.(*ReplicateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataKeeperService_CheckFileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServiceServer).CheckFileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datakeeper.DataKeeperService/CheckFileExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServiceServer).CheckFileExists(ctx, req.(*CheckFileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataKeeperService_DownloadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperServiceServer).DownloadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datakeeper.DataKeeperService/DownloadChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperServiceServer).DownloadChunk(ctx, req.(*DownloadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataKeeperService_ServiceDesc is the grpc.ServiceDesc for DataKeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataKeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datakeeper.DataKeeperService",
	HandlerType: (*DataKeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFile",
			Handler:    _DataKeeperService_TransferFile_Handler,
		},
		{
			MethodName: "ReplicateFile",
			Handler:    _DataKeeperService_ReplicateFile_Handler,
		},
		{
			MethodName: "CheckFileExists",
			Handler:    _DataKeeperService_CheckFileExists_Handler,
		},
		{
			MethodName: "DownloadChunk",
			Handler:    _DataKeeperService_DownloadChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/grpc/datakeeper/datakeeper.proto",
}

// FileSaveServiceClient is the client API for FileSaveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileSaveServiceClient interface {
	SaveFile(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type fileSaveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSaveServiceClient(cc grpc.ClientConnInterface) FileSaveServiceClient {
	return &fileSaveServiceClient{cc}
}

func (c *fileSaveServiceClient) SaveFile(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/datakeeper.FileSaveService/SaveFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSaveServiceServer is the server API for FileSaveService service.
// All implementations must embed UnimplementedFileSaveServiceServer
// for forward compatibility
type FileSaveServiceServer interface {
	SaveFile(context.Context, *FileSaveRequest) (*SuccessResponse, error)
	mustEmbedUnimplementedFileSaveServiceServer()
}

// UnimplementedFileSaveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileSaveServiceServer struct {
}

func (UnimplementedFileSaveServiceServer) SaveFile(context.Context, *FileSaveRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedFileSaveServiceServer) mustEmbedUnimplementedFileSaveServiceServer() {}

// UnsafeFileSaveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSaveServiceServer will
// result in compilation errors.
type UnsafeFileSaveServiceServer interface {
	mustEmbedUnimplementedFileSaveServiceServer()
}

func RegisterFileSaveServiceServer(s grpc.ServiceRegistrar, srv FileSaveServiceServer) {
	s.RegisterService(&FileSaveService_ServiceDesc, srv)
}

func _FileSaveService_SaveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSaveServiceServer).SaveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datakeeper.FileSaveService/SaveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSaveServiceServer).SaveFile(ctx, req.(*FileSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileSaveService_ServiceDesc is the grpc.ServiceDesc for FileSaveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSaveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datakeeper.FileSaveService",
	HandlerType: (*FileSaveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveFile",
			Handler:    _FileSaveService_SaveFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/grpc/datakeeper/datakeeper.proto",
}
