// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.0
// source: src/grpc/master/master.proto

package master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MasterTrackerService_RegisterFile_FullMethodName         = "/master.MasterTrackerService/RegisterFile"
	MasterTrackerService_UpdateFileLocation_FullMethodName   = "/master.MasterTrackerService/UpdateFileLocation"
	MasterTrackerService_UpdateDataNodeStatus_FullMethodName = "/master.MasterTrackerService/UpdateDataNodeStatus"
	MasterTrackerService_LookupFile_FullMethodName           = "/master.MasterTrackerService/LookupFile"
)

// MasterTrackerServiceClient is the client API for MasterTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterTrackerServiceClient interface {
	// RPC method for registering a new file
	RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*RegisterFileResponse, error)
	// RPC method for updating file location
	UpdateFileLocation(ctx context.Context, in *UpdateFileLocationRequest, opts ...grpc.CallOption) (*UpdateFileLocationResponse, error)
	// RPC method for updating data node status
	UpdateDataNodeStatus(ctx context.Context, in *UpdateDataNodeStatusRequest, opts ...grpc.CallOption) (*UpdateDataNodeStatusResponse, error)
	// RPC method for looking up file location
	LookupFile(ctx context.Context, in *LookupFileRequest, opts ...grpc.CallOption) (*LookupFileResponse, error)
}

type masterTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterTrackerServiceClient(cc grpc.ClientConnInterface) MasterTrackerServiceClient {
	return &masterTrackerServiceClient{cc}
}

func (c *masterTrackerServiceClient) RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*RegisterFileResponse, error) {
	out := new(RegisterFileResponse)
	err := c.cc.Invoke(ctx, MasterTrackerService_RegisterFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServiceClient) UpdateFileLocation(ctx context.Context, in *UpdateFileLocationRequest, opts ...grpc.CallOption) (*UpdateFileLocationResponse, error) {
	out := new(UpdateFileLocationResponse)
	err := c.cc.Invoke(ctx, MasterTrackerService_UpdateFileLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServiceClient) UpdateDataNodeStatus(ctx context.Context, in *UpdateDataNodeStatusRequest, opts ...grpc.CallOption) (*UpdateDataNodeStatusResponse, error) {
	out := new(UpdateDataNodeStatusResponse)
	err := c.cc.Invoke(ctx, MasterTrackerService_UpdateDataNodeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterTrackerServiceClient) LookupFile(ctx context.Context, in *LookupFileRequest, opts ...grpc.CallOption) (*LookupFileResponse, error) {
	out := new(LookupFileResponse)
	err := c.cc.Invoke(ctx, MasterTrackerService_LookupFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterTrackerServiceServer is the server API for MasterTrackerService service.
// All implementations must embed UnimplementedMasterTrackerServiceServer
// for forward compatibility
type MasterTrackerServiceServer interface {
	// RPC method for registering a new file
	RegisterFile(context.Context, *RegisterFileRequest) (*RegisterFileResponse, error)
	// RPC method for updating file location
	UpdateFileLocation(context.Context, *UpdateFileLocationRequest) (*UpdateFileLocationResponse, error)
	// RPC method for updating data node status
	UpdateDataNodeStatus(context.Context, *UpdateDataNodeStatusRequest) (*UpdateDataNodeStatusResponse, error)
	// RPC method for looking up file location
	LookupFile(context.Context, *LookupFileRequest) (*LookupFileResponse, error)
	mustEmbedUnimplementedMasterTrackerServiceServer()
}

// UnimplementedMasterTrackerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMasterTrackerServiceServer struct {
}

func (UnimplementedMasterTrackerServiceServer) RegisterFile(context.Context, *RegisterFileRequest) (*RegisterFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFile not implemented")
}
func (UnimplementedMasterTrackerServiceServer) UpdateFileLocation(context.Context, *UpdateFileLocationRequest) (*UpdateFileLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFileLocation not implemented")
}
func (UnimplementedMasterTrackerServiceServer) UpdateDataNodeStatus(context.Context, *UpdateDataNodeStatusRequest) (*UpdateDataNodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataNodeStatus not implemented")
}
func (UnimplementedMasterTrackerServiceServer) LookupFile(context.Context, *LookupFileRequest) (*LookupFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupFile not implemented")
}
func (UnimplementedMasterTrackerServiceServer) mustEmbedUnimplementedMasterTrackerServiceServer() {}

// UnsafeMasterTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterTrackerServiceServer will
// result in compilation errors.
type UnsafeMasterTrackerServiceServer interface {
	mustEmbedUnimplementedMasterTrackerServiceServer()
}

func RegisterMasterTrackerServiceServer(s grpc.ServiceRegistrar, srv MasterTrackerServiceServer) {
	s.RegisterService(&MasterTrackerService_ServiceDesc, srv)
}

func _MasterTrackerService_RegisterFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServiceServer).RegisterFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerService_RegisterFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServiceServer).RegisterFile(ctx, req.(*RegisterFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerService_UpdateFileLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServiceServer).UpdateFileLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerService_UpdateFileLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServiceServer).UpdateFileLocation(ctx, req.(*UpdateFileLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerService_UpdateDataNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServiceServer).UpdateDataNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerService_UpdateDataNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServiceServer).UpdateDataNodeStatus(ctx, req.(*UpdateDataNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterTrackerService_LookupFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterTrackerServiceServer).LookupFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterTrackerService_LookupFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterTrackerServiceServer).LookupFile(ctx, req.(*LookupFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterTrackerService_ServiceDesc is the grpc.ServiceDesc for MasterTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master.MasterTrackerService",
	HandlerType: (*MasterTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFile",
			Handler:    _MasterTrackerService_RegisterFile_Handler,
		},
		{
			MethodName: "UpdateFileLocation",
			Handler:    _MasterTrackerService_UpdateFileLocation_Handler,
		},
		{
			MethodName: "UpdateDataNodeStatus",
			Handler:    _MasterTrackerService_UpdateDataNodeStatus_Handler,
		},
		{
			MethodName: "LookupFile",
			Handler:    _MasterTrackerService_LookupFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/grpc/master/master.proto",
}
